spring:
  datasource:
    url: jdbc:mysql://localhost:3307/pdaetf?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: pda
    password: pda1234!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jackson:
    time-zone: UTC
server:
  port: 8080